// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIAttendanceSystem.Models
{
    [Index(nameof(AttendanceDate), nameof(StudentId), Name = "AK_Attendances_AttendanceDate_StudentId", IsUnique = true)]
    public partial class Attendance
    {
        [Key]
        public int StudentId { get; set; }
        [Key]
        public DateTime AttendanceDate { get; set; }
        public TimeSpan? ArrivalTime { get; set; }
        public TimeSpan? LeaveTime { get; set; }

        [ForeignKey(nameof(StudentId))]
        [InverseProperty("Attendances")]
        public virtual Student Student { get; set; }
    }
}