// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIAttendanceSystem.Models
{
    [Index("ArrivalTime", "AttendanceDate", "StaffId", Name = "AK_buildingAffairsAttendances_ArrivalTime_AttendanceDate_StaffId", IsUnique = true)]
    public partial class buildingAffairsAttendance
    {
        [Key]
        public int StaffId { get; set; }
        [Key]
        public DateTime AttendanceDate { get; set; }
        [Key]
        public TimeSpan ArrivalTime { get; set; }
        public TimeSpan? LeaveTime { get; set; }

        [ForeignKey("StaffId")]
        [InverseProperty("buildingAffairsAttendances")]
        public virtual BuildingAffairsStaff Staff { get; set; }
    }
}