// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIAttendanceSystem.Models
{
    [Index("StudentId", Name = "IX_Comments_StudentId")]
    [Index("UserId", Name = "IX_Comments_UserId")]
    public partial class Comment
    {
        [Key]
        public int Id { get; set; }
        public string Body { get; set; }
        public int CommentType { get; set; }
        public DateTime CommentDate { get; set; }
        public int StudentId { get; set; }
        public string UserId { get; set; }

        [ForeignKey("StudentId")]
        [InverseProperty("Comments")]
        public virtual Student Student { get; set; }
    }
}