// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIAttendanceSystem.Models
{
    [Index("IntakeId", Name = "IX_Departments_IntakeId")]
    [Index("SupervisorId", Name = "IX_Departments_SupervisorId")]
    public partial class Department
    {
        public Department()
        {
            Instructors = new HashSet<Instructor>();
            Schedules = new HashSet<Schedule>();
            Students = new HashSet<Student>();
            Subjects = new HashSet<Subject>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(15)]
        public string ShortName { get; set; }
        [StringLength(100)]
        public string FullName { get; set; }
        public DateTime? AttendanceEndDate { get; set; }
        public int? SupervisorId { get; set; }
        public int? IntakeId { get; set; }
        public bool Status { get; set; }
        public string Code { get; set; }

        [ForeignKey("SupervisorId")]
        [InverseProperty("Departments")]
        public virtual Instructor Supervisor { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<Instructor> Instructors { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<Student> Students { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}