// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIAttendanceSystem.Models
{
    [Index("DepartmentId", Name = "IX_Instructors_DepartmentId")]
    public partial class Instructor
    {
        public Instructor()
        {
            Departments = new HashSet<Department>();
            studentPermissions = new HashSet<studentPermission>();
        }

        [Key]
        public int InstructorId { get; set; }
        public string Id { get; set; }
        public string InstName { get; set; }
        public int? DepartmentId { get; set; }

        [ForeignKey("DepartmentId")]
        [InverseProperty("Instructors")]
        public virtual Department Department { get; set; }
        [InverseProperty("Supervisor")]
        public virtual ICollection<Department> Departments { get; set; }
        [InverseProperty("Instructor")]
        public virtual ICollection<studentPermission> studentPermissions { get; set; }
    }
}