// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIAttendanceSystem.Models
{
    [Index(nameof(DepartmentId), Name = "IX_Schedules_DepartmentId")]
    public partial class Schedule
    {
        [Key]
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public DateTime ScheduleDate { get; set; }
        public int LectPeriod { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("Schedules")]
        public virtual Department Department { get; set; }
    }
}