// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIAttendanceSystem.Models
{
    [Index(nameof(InstructorId), Name = "IX_studentPermissions_InstructorId")]
    [Index(nameof(StudentId), Name = "IX_studentPermissions_StudentId")]
    public partial class studentPermission
    {
        [Key]
        public int Id { get; set; }
        public int StudentId { get; set; }
        public DateTime PermissionDate { get; set; }
        public string Note { get; set; }
        public int PermissionState { get; set; }
        public int PermissionType { get; set; }
        public int? InstructorId { get; set; }

        [ForeignKey(nameof(InstructorId))]
        [InverseProperty("studentPermissions")]
        public virtual Instructor Instructor { get; set; }
        [ForeignKey(nameof(StudentId))]
        [InverseProperty("studentPermissions")]
        public virtual Student Student { get; set; }
    }
}