// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIAttendanceSystem.Models
{
    [Index(nameof(DepartmentId), Name = "IX_Students_DepartmentId")]
    public partial class Student
    {
        public Student()
        {
            Attendances = new HashSet<Attendance>();
            Comments = new HashSet<Comment>();
            studentPermissions = new HashSet<studentPermission>();
        }

        [Key]
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int StudentStatus { get; set; }
        public string Id { get; set; }
        public int? DepartmentId { get; set; }
        [Range(1,3)]
        public int? SecNo { get; set; }
        public string Address { get; set; }
        public string Faculty { get; set; }
        public string University { get; set; }
        public string Specialization { get; set; }
        public int GraduationYear { get; set; }
        public string GraduationGrade { get; set; }
        public string Mobile { get; set; }
        public string HomePhone { get; set; }
        public string MilitaryStatusName { get; set; }
        public string Code { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("Students")]
        public virtual Department Department { get; set; }
        [InverseProperty("Student")]
        public virtual Document Document { get; set; }
        [InverseProperty(nameof(Attendance.Student))]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [InverseProperty(nameof(Comment.Student))]
        public virtual ICollection<Comment> Comments { get; set; }
        [InverseProperty(nameof(studentPermission.Student))]
        public virtual ICollection<studentPermission> studentPermissions { get; set; }
    }
}